<?php

/* 
 * footer.inc
 * footer for all pages of myX
 * (c) Joaquin Javier ESTEBAN MARTINEZ
 * last update: 2017-12-21
 */

echo <<<HTML
            <footer><!-- footer {{ -->
                <p>myX - &copy; Joaquín Javier Esteban Martínez 2018</p>
            </footer><!-- }} footer -->


HTML;

include 'aside.inc';

echo <<<HTML
        </div><!-- }} div container -->
    </body>
</html>

HTML;

?>