/* myXData.sql
 * myX sample data
 * (c) Joaquin Javier ESTEBAN MARTINEZ
 * last update: 2018-01-23
 */
INSERT INTO `myX`.`users` VALUES (1, 'jesteban1972', 'Aquiles0184', 'jesteban1972@me.com', 1);
INSERT INTO `myX`.`users` VALUES (2, 'Fulano', 'f', 'fulano@gmail.com', 1);

INSERT INTO `myX`.`countries` VALUES (1, 'Turquía', 2);
INSERT INTO `myX`.`countries` VALUES (2, 'Grecia', 2);
INSERT INTO `myX`.`countries` VALUES (3, 'Italia', 2);

INSERT INTO `myX`.`kinds` VALUES (1, '(generic)', 2);

INSERT INTO `myX`.`loca` VALUES(1, '', 'Olimpia: Templo de Zeus', 2, 1, 'El templo de Zeus en Olimpia albergaba la famosa estatua crisoelefantina del dios, obra del no menos famoso Fidias. Esta estatua era considerada como una de las siete maravillas del mundo antiguo', 3, "Archea Olimpia 270 65, Greece",'37.637932, 21.630238','37.637932, 21.630238', "odysseus.culture.gr", 2);
INSERT INTO `myX`.`loca` VALUES(2, '', 'Delfos: Templo de Apolo', 2, 1, 'El templo de Apolo en Delfos era el lugar central del santuario y donde tenía lugar el famoso oráculo', 3, '','38.482288, 22.501146','','',2);
INSERT INTO `myX`.`loca` VALUES(3, '', 'Éfeso: Templo de Artemisa', 1, 1, 'El templo de Artemisa en Éfeso era una de las siete maravillas del mundo antiguo', 3, '','37.949887, 27.363383','','',2);
INSERT INTO `myX`.`loca` VALUES(4, '', 'Atenas: Partenón', 2, 1, 'El Partenón de Atenas era una de las siete maravillas del mundo antiguo', 3, '','37.971482, 23.726625', '','',2);
INSERT INTO `myX`.`loca` VALUES(5, "", "Aphrodisias: Templo de Afrodita", 1, 1, "El templo de Afrodita es y sigue siendo el punto principal del sitio, pero el carácter del edificio se alteró cuando se convirtió en una basílica cristiana. Los escultores de Afrodisias eran célebres y se beneficiaron de una gran abundancia de mármol en las montañas cercanas. La escuela de escultura de la ciudad produjo bastantes obras, muchas de las cuales todavía se pueden apreciar en el sitio y en el museo de la ciudad. Durante las excavaciones se encontraron muchas estatuas completas en el área del ágora y estatuas sin terminar en un área que señala el sitio de una escuela de escultura. También se han hallado sarcófagos en varios puntos de la ciudad, la mayor parte de ellos con diseños que constan de guirnaldas y columnas, al igual que pilares con diseños descritos como «manuscritos humanos» o «vivientes», representando personas, pájaros y animales envueltos en hojas de acanto.<br />En el sitio arqueológico alrededor del templo se pueden encontrar rincones ideales para mantener sexo.", 3, "Geyre Mahallesi, Kuyucak Tavas Yolu, 09385 Karacasu/Aydın, Turkey", "37.710071, 28.725108", "", "www.muze.gov.tr/aphrodisias", 2);
INSERT INTO `myX`.`loca` VALUES(6, '', 'Sunio: Templo de Poseidón', 1, 1, 'El templo de Poseidón de Sunio era lo primero que veían los navegantes cuando se aproximaban al Ática', 3, '','37.650153, 24.024572','','',2);
INSERT INTO `myX`.`loca` VALUES(7, '', 'Monte Cyllene: Templo de Hermes', 1, 1, 'El templo de Hermes en el Monte Cyllene se construyó en el lugar en que, según la tradición, nació el dios', 3, '','37.939785, 22.395832','','',2);
INSERT INTO `myX`.`loca` VALUES(8, '', 'Argos: Templo de Hera', 1, 1, 'El templo de Hera en Argos bla bla bla', 3, '','37.691998, 22.775001', '','',2);
INSERT INTO `myX`.`loca` VALUES(9, '', 'Roma: Templo de Marte Ultore', 3, 1, 'El templo de Marte Ultore en Roma bla bla bla', 3, '','41.894396, 12.486927', '','',2);
INSERT INTO `myX`.`loca` VALUES(10, '', 'Atenas: Templo de Hefesto (aka Thisio)', 1, 1, 'El templo de Hefesto en Atenas, erróneamente llamado Thisio, bla bla bla', 3, '','37.975588, 23.721417','','',2);
INSERT INTO `myX`.`loca` VALUES(11, '', 'Naxos: Templo de Démeter', 1, 1, 'El templo de Démeter en Naxos bla bla bla..', 3, '','37.029108, 25.431321', '','',2);
INSERT INTO `myX`.`loca` VALUES(12, '', 'Naxos: Templo de Dionisio', 1, 1, 'El templo de Dionisio en Naxos bla bla bla..', 3 ,'','37.077697, 25.380779', '','',2);

INSERT INTO `myX`.`practica` VALUES (1, "", 1, "2018-05-15", "a", "Excitante cunnilingus con eyaculación", 4, "Esta es la experiencia número uno, experiencia vivida con Actea. Aconteció que bla bla bla...", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (2, "", 2, "2018-05-16", "a", "Coito en trío desprotegido sin eyaculación", 3, "Esta es la experiencia número dos, experiencia en trío vivida con Actea y con Eunice. Aconteció que bla bla bla...", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (3, "", 3, "2018-05-17", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (4, "", 4, "2018-05-18", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (5, "", 5, "2018-05-19", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (6, "", 6, "2018-05-20", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (7, "", 7, "2018-05-21", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8, "", 8, "2018-05-22", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (9, "", 9, "2018-05-23", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (10, "", 10, "2018-05-24", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (11, "", 11, "2018-05-25", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (12, "", 12, "2018-05-26", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (13, "", 1, "2018-05-27", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (14, "", 2, "2018-05-28", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (15, "", 3, "2018-05-29", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (16, "", 4, "2018-05-30", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (17, "", 5, "2018-05-31", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (18, "", 6, "2018-06-01", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (19, "", 7, "2018-06-02", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (20, "", 8, "2018-06-03", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (21, "", 9, "2018-06-04", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (22, "", 10, "2018-06-05", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (23, "", 11, "2018-06-06", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (24, "", 12, "2018-06-07", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (25, "", 1, "2018-06-08", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (26, "", 2, "2018-06-09", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (27, "", 3, "2018-06-10", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (28, "", 4, "2018-06-11", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (29, "", 5, "2018-06-12", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (30, "", 6, "2018-06-13", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (31, "", 7, "2018-06-14", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (32, "", 8, "2018-06-15", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (33, "", 9, "2018-06-16", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (34, "", 10, "2018-06-17", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (35, "", 11, "2018-06-18", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (36, "", 12, "2018-06-19", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (37, "", 1, "2018-06-20", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (38, "", 2, "2018-06-21", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (39, "", 3, "2018-06-22", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (40, "", 4, "2018-06-23", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (41, "", 5, "2018-06-24", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (42, "", 6, "2018-06-25", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (43, "", 7, "2018-06-26", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (44, "", 8, "2018-06-27", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (45, "", 9, "2018-06-28", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (46, "", 10, "2018-06-29", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (47, "", 11, "2018-06-30", "a", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (48, "", 12, "2018-05-15", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (49, "", 1, "2018-05-16", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (50, "", 2, "2018-05-17", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (51, "", 3, "2018-05-18", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (52, "", 4, "2018-05-19", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (53, "", 5, "2018-05-20", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (54, "", 1, "2018-05-21", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (55, "", 1, "2018-05-22", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (56, "", 1, "2018-05-23", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (57, "", 6, "2018-05-24", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (58, "", 7, "2018-05-25", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (59, "", 8, "2018-05-26", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (60, "", 9, "2018-05-27", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (61, "", 10, "2018-05-28", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (62, "", 11, "2018-05-29", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (63, "", 12, "2018-05-30", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (64, "", 1, "2018-05-31", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (65, "", 2, "2018-06-01", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (66, "", 3, "2018-06-02", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (67, "", 4, "2018-06-03", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (68, "", 5, "2018-06-04", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (69, "", 6, "2018-06-05", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (70, "", 7, "2018-06-06", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (71, "", 8, "2018-06-07", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (72, "", 9, "2018-06-08", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (73, "", 10, "2018-06-09", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (74, "", 11, "2018-06-10", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (75, "", 12, "2018-06-11", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (76, "", 1, "2018-06-12", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (77, "", 2, "2018-06-13", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (78, "", 3, "2018-06-14", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (79, "", 4, "2018-06-15", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (80, "", 5, "2018-06-16", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (81, "", 6, "2018-06-17", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (82, "", 7, "2018-06-18", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (83, "", 8, "2018-06-19", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (84, "", 9, "2018-06-20", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (85, "", 10, "2018-06-21", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (86, "", 11, "2018-06-22", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (87, "", 12, "2018-06-23", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (88, "", 1, "2018-06-24", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (89, "", 2, "2018-06-25", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (90, "", 3, "2018-06-26", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (91, "", 4, "2018-06-27", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (92, "", 5, "2018-06-28", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (93, "", 6, "2018-06-29", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (94, "", 7, "2018-06-30", "b", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (95, "", 8, "2018-05-15", "c", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (96, "", 9, "2018-05-16", "c", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (97, "", 10, "2018-05-17", "c", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (98, "", 11, "2018-05-18", "c", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (99, "", 12, "2018-05-19", "c", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (100, "", 1, "2018-05-20", "c", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);

INSERT INTO `myX`.`amores` VALUES (1, "", "Actea, la de los acantilados", 2, "Actea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "Skype: actea1973; Badoo: actea1973; Instagram: actea1973", "Actea María Pérez Pérez", 0, "(+34) 661 662 663", "actea@gmail.com", "fecha de nacimiento: 1973-01-01", 2);
INSERT INTO `myX`.`amores` VALUES (2, "", "Ágava, la resplandeciente", 2, "Ágava es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (3, "", "Amatea, la de hermosos bucles", 2, "Amatea es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (4, "", "Anfínoma", 2, "Anfínoma es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5, "", "Anfítoa", 2, "Anfítoa es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (6, "", "Anfítrite, la de bellos tobillos", 2, "Anfítrite es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (7, "", "Apseudes", 2, "Apseudes es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (8, "", "Autónoe, la que se entiende a sí misma", 2, "Autónoe es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (9, "", "Calianasa", 2, "Calianasa es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (10, "", "Calianira", 2, "Calianira es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (11, "", "Calipso", 2, "Calipso es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (12, "", "Ceto", 2, "Ceto es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (13, "", "Cimatolega, la que calma el oleaje", 2, "Cimatolega es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (14, "", "Cimo, la de las olas", 2, "Cimo es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (15, "", "Cimódoce, la que recibe las olas, la que calma sin esfuerzo el oleaje en el sombrío ponto y las rafagas de los vientos huracanados", 2, "Cimódoce es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (16, "", "Cimótoa, la de rápidas olas", 2, "Cimótoa es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (17, "", "Clímena", 2, "Clímena es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (18, "", "Clío", 2, "Clío es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (19, "", "Cranto", 2, "Cranto así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (20, "", "Dero", 2, "Dero es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (21, "", "Dexamena", 2, "Dexamena es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (22, "", "Dinámena, la potente", 2, "Dinámena es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (23, "", "Dione", 2, "Dione es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (24, "", "Doris, la que regala", 2, "Doris es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (25, "", "Doto, la dadivosa", 2, "Doto es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (26, "", "Érato, la deliciosa", 2, "Érato es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (27, "", "Espío, la de las grutas", 2, "Espío es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (28, "", "Eucranta, la que concede coronar el fin", 2, "Eucranta es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (29, "", "Eudora, la que da prosperidad", 2, "Eudora es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (30, "", "Eulímene, la de buen puerto", 2, "Eulímene es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (31, "", "Eumolpe", 2, "Eumolpe es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (32, "", "Eunice, la de fácil victoria, la de rosados brazos", 2, "Eunice es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (33, "", "Eupompa, la de feliz viaje", 2, "Eupompa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (34, "", "Eurídice", 2, "Eurídice es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (35, "", "Evágora,la elocuente", 2, "Evágora es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (36, "", "Evarna, la rica en ganado, la de encantadora figura y belleza sin tacha", 2, "Evarna es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (37, "", "Éyone, la del fondeadero", 2, "Éynoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (38, "", "Ferusa, la que lleva", 2, "Ferusa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (39, "", "Galatea, la hermosa, la muy ilustre", 2, "Galatea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (40, "", "Galena, la calma", 2, "Galena es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (41, "", "Glauca, la azulada", 2, "Glauca es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (42, "", "Glaucónoma, la del azulado prado, la risueña", 2, "Glaucónoma es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (43, "", "Halía, la salada, la amable, la de inmensos ojos", 2, "Halía es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (44, "", "Halimeda, la que cuida del mar, la de bella corona", 2, "Halimeda es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (45, "", "Hipónoe, la inteligente como un caballo, la de rosados brazos", 2, "Hipónoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (46, "", "Hipótoa, la veloz como un caballo, la encantadora", 2, "Hipótoa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (47, "", "Iera", 2, "Iera es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (48, "", "Laomedea, la que cuida del pueblo", 2, "Laomedea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (49, "", "Leágora, la de la suave palabra", 2, "Leágora es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (50, "", "Limnoria", 2, "Limnoria es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (51, "", "Lisiánasa, la señora de la libertad", 2, "Lisiánasa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (52, "", "Mélita, la dulce, la graciosa", 2, "Mélita es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (53, "", "Menipa, la del vigor de caballo, la divina", 2, "Menipa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (54, "", "Mera", 2, "Mera es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (55, "", "Nausítoe", 2, "Nausítoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (56, "", "Nemertes, la sin tacha, la que tiene la inteligencia de su inmortal padre", 2, "Nemertes es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (57, "", "Neómeris", 2, "Neómeris es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (58, "", "Nesea, la isleña", 2, "Nesea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (59, "", "Neso, la isla", 2, "Neso es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (60, "", "Oritía", 2, "Oritía es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (61, "", "Pánopa, la que todo lo ve", 2, "Pánopa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (62, "", "Pasítea, la muy divina", 2, "Pasítea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (63, "", "Plexaura", 2, "Plexaura es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (64, "", "Ploto, la naviera", 2, "Ploto es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (65, "", "Polínoe, la que mucho entiende", 2, "Polínoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (66, "", "Polínome", 2, "Polínome es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (67, "", "Pontomedusa", 2, "Pontomedusa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (68, "", "Prónoe, la previsora", 2, "Prónoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (69, "", "Proto, la primera", 2, "Proto es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (70, "", "Protomedea, la primera en pensamientos", 2, "Protomedea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (71, "", "Protoporea, la que permite atravesar el ponto", 2, "Protoporea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (72, "", "Psámata, la arenosa, la de gracioso porte", 2, "Psámata es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (73, "", "Sao, la salvadora", 2, "Sao es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (74, "", "Talía", 2, "Talía es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (75, "", "Temisto, la observadora de las leyes divinas", 2, "Temisto es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (76, "", "Tetis", 2, "Tetis es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (77, "", "Toa, la rápida", 2, "Toa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (78, "", "Yanasa", 2, "Yanasa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (79, "", "Yanira", 2, "Yanira es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (80, "", "Yone", 2, "Yone es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "Tiene unos genitales tal y tal", 3, "", "", 0, "", "", "", 2);

INSERT INTO `myX`.`assignations` VALUES (1, 2);
INSERT INTO `myX`.`assignations` VALUES (2, 2);
INSERT INTO `myX`.`assignations` VALUES (3, 2);
INSERT INTO `myX`.`assignations` VALUES (4, 2);
INSERT INTO `myX`.`assignations` VALUES (5, 2);
INSERT INTO `myX`.`assignations` VALUES (6, 2);
INSERT INTO `myX`.`assignations` VALUES (7, 2);
INSERT INTO `myX`.`assignations` VALUES (8, 2);
INSERT INTO `myX`.`assignations` VALUES (9, 2);
INSERT INTO `myX`.`assignations` VALUES (10, 2);
INSERT INTO `myX`.`assignations` VALUES (11, 2);
INSERT INTO `myX`.`assignations` VALUES (12, 2);
INSERT INTO `myX`.`assignations` VALUES (13, 2);
INSERT INTO `myX`.`assignations` VALUES (14, 2);
INSERT INTO `myX`.`assignations` VALUES (15, 2);
INSERT INTO `myX`.`assignations` VALUES (16, 2);
INSERT INTO `myX`.`assignations` VALUES (17, 2);
INSERT INTO `myX`.`assignations` VALUES (18, 2);
INSERT INTO `myX`.`assignations` VALUES (19, 2);
INSERT INTO `myX`.`assignations` VALUES (20, 2);
INSERT INTO `myX`.`assignations` VALUES (21, 1);
INSERT INTO `myX`.`assignations` VALUES (22, 2);
INSERT INTO `myX`.`assignations` VALUES (23, 3);
INSERT INTO `myX`.`assignations` VALUES (24, 4);
INSERT INTO `myX`.`assignations` VALUES (25, 5);
INSERT INTO `myX`.`assignations` VALUES (26, 6);
INSERT INTO `myX`.`assignations` VALUES (27, 7);
INSERT INTO `myX`.`assignations` VALUES (28, 8);
INSERT INTO `myX`.`assignations` VALUES (29, 9);
INSERT INTO `myX`.`assignations` VALUES (30, 10);
INSERT INTO `myX`.`assignations` VALUES (31, 11);
INSERT INTO `myX`.`assignations` VALUES (32, 12);
INSERT INTO `myX`.`assignations` VALUES (33, 13);
INSERT INTO `myX`.`assignations` VALUES (34, 14);
INSERT INTO `myX`.`assignations` VALUES (35, 15);
INSERT INTO `myX`.`assignations` VALUES (36, 16);
INSERT INTO `myX`.`assignations` VALUES (37, 17);
INSERT INTO `myX`.`assignations` VALUES (38, 18);
INSERT INTO `myX`.`assignations` VALUES (39, 19);
INSERT INTO `myX`.`assignations` VALUES (40, 20);
INSERT INTO `myX`.`assignations` VALUES (41, 21);
INSERT INTO `myX`.`assignations` VALUES (42, 22);
INSERT INTO `myX`.`assignations` VALUES (43, 23);
INSERT INTO `myX`.`assignations` VALUES (44, 24);
INSERT INTO `myX`.`assignations` VALUES (45, 25);
INSERT INTO `myX`.`assignations` VALUES (46, 26);
INSERT INTO `myX`.`assignations` VALUES (47, 27);
INSERT INTO `myX`.`assignations` VALUES (48, 28);
INSERT INTO `myX`.`assignations` VALUES (49, 29);
INSERT INTO `myX`.`assignations` VALUES (50, 30);
INSERT INTO `myX`.`assignations` VALUES (51, 31);
INSERT INTO `myX`.`assignations` VALUES (52, 32);
INSERT INTO `myX`.`assignations` VALUES (53, 33);
INSERT INTO `myX`.`assignations` VALUES (54, 34);
INSERT INTO `myX`.`assignations` VALUES (55, 35);
INSERT INTO `myX`.`assignations` VALUES (56, 36);
INSERT INTO `myX`.`assignations` VALUES (57, 37);
INSERT INTO `myX`.`assignations` VALUES (58, 38);
INSERT INTO `myX`.`assignations` VALUES (59, 39);
INSERT INTO `myX`.`assignations` VALUES (60, 40);
INSERT INTO `myX`.`assignations` VALUES (61, 41);
INSERT INTO `myX`.`assignations` VALUES (62, 42);
INSERT INTO `myX`.`assignations` VALUES (63, 43);
INSERT INTO `myX`.`assignations` VALUES (64, 44);
INSERT INTO `myX`.`assignations` VALUES (65, 45);
INSERT INTO `myX`.`assignations` VALUES (66, 46);
INSERT INTO `myX`.`assignations` VALUES (67, 47);
INSERT INTO `myX`.`assignations` VALUES (68, 48);
INSERT INTO `myX`.`assignations` VALUES (69, 49);
INSERT INTO `myX`.`assignations` VALUES (70, 50);
INSERT INTO `myX`.`assignations` VALUES (71, 51);
INSERT INTO `myX`.`assignations` VALUES (72, 52);
INSERT INTO `myX`.`assignations` VALUES (73, 53);
INSERT INTO `myX`.`assignations` VALUES (74, 54);
INSERT INTO `myX`.`assignations` VALUES (75, 55);
INSERT INTO `myX`.`assignations` VALUES (76, 56);
INSERT INTO `myX`.`assignations` VALUES (77, 57);
INSERT INTO `myX`.`assignations` VALUES (78, 58);
INSERT INTO `myX`.`assignations` VALUES (79, 59);
INSERT INTO `myX`.`assignations` VALUES (80, 60);
INSERT INTO `myX`.`assignations` VALUES (81, 61);
INSERT INTO `myX`.`assignations` VALUES (82, 62);
INSERT INTO `myX`.`assignations` VALUES (83, 63);
INSERT INTO `myX`.`assignations` VALUES (84, 64);
INSERT INTO `myX`.`assignations` VALUES (85, 65);
INSERT INTO `myX`.`assignations` VALUES (86, 66);
INSERT INTO `myX`.`assignations` VALUES (87, 67);
INSERT INTO `myX`.`assignations` VALUES (88, 68);
INSERT INTO `myX`.`assignations` VALUES (89, 69);
INSERT INTO `myX`.`assignations` VALUES (90, 70);
INSERT INTO `myX`.`assignations` VALUES (91, 71);
INSERT INTO `myX`.`assignations` VALUES (92, 72);
INSERT INTO `myX`.`assignations` VALUES (93, 73);
INSERT INTO `myX`.`assignations` VALUES (94, 74);
INSERT INTO `myX`.`assignations` VALUES (95, 75);
INSERT INTO `myX`.`assignations` VALUES (96, 76);
INSERT INTO `myX`.`assignations` VALUES (97, 77);
INSERT INTO `myX`.`assignations` VALUES (98, 78);
INSERT INTO `myX`.`assignations` VALUES (99, 79);
INSERT INTO `myX`.`assignations` VALUES (100, 80);
