/* myXData.sql
 * myX sample data
 * (c) Joaquin Javier ESTEBAN MARTINEZ
 * last update: 2018-02-08
 */
/*
INSERT INTO `myX`.`users` VALUES (1, 'jesteban1972', 'Aquiles0184', 'jesteban1972@me.com', 1, '', '', '', '', 1, 25, 1);
INSERT INTO `myX`.`users` VALUES (2, 'Fulano', 'f', 'fulano@gmail.com', 1, '', '', '', '', 1, 25, 1);
*/

INSERT INTO `myX`.`countries` VALUES (18, 'Turquía', 2);
INSERT INTO `myX`.`countries` VALUES (19, 'Grecia', 2);
INSERT INTO `myX`.`countries` VALUES (20, 'Italia', 2);
/* values 1..17 reserved by Sarkodeiktes */

INSERT INTO `myX`.`kinds` VALUES (10, '(generic)', 2);
/* values 1..9 reserved by Sarkodeiktes */

INSERT INTO `myX`.`loca` VALUES(734, '', 'Olimpia: Templo de Zeus', 19, 10, 'El templo de Zeus en Olimpia albergaba la famosa estatua crisoelefantina del dios, obra del no menos famoso Fidias. Esta estatua era considerada como una de las siete maravillas del mundo antiguo', 3, "Archea Olimpia 270 65, Greece",'37.637932, 21.630238','37.637932, 21.630238', "odysseus.culture.gr", 2);
INSERT INTO `myX`.`loca` VALUES(735, '', 'Delfos: Templo de Apolo', 19, 10, 'El templo de Apolo en Delfos era el lugar central del santuario y donde tenía lugar el famoso oráculo', 3, '','38.482288, 22.501146','','',2);
INSERT INTO `myX`.`loca` VALUES(736, '', 'Éfeso: Templo de Artemisa', 18, 10, 'El templo de Artemisa en Éfeso era una de las siete maravillas del mundo antiguo', 3, '','37.949887, 27.363383','','',2);
INSERT INTO `myX`.`loca` VALUES(737, '', 'Atenas: Partenón', 19, 10, 'El Partenón de Atenas era una de las siete maravillas del mundo antiguo', 3, '','37.971482, 23.726625', '','',2);
INSERT INTO `myX`.`loca` VALUES(738, "", "Aphrodisias: Templo de Afrodita", 18, 10, "El templo de Afrodita es y sigue siendo el punto principal del sitio, pero el carácter del edificio se alteró cuando se convirtió en una basílica cristiana. Los escultores de Afrodisias eran célebres y se beneficiaron de una gran abundancia de mármol en las montañas cercanas. La escuela de escultura de la ciudad produjo bastantes obras, muchas de las cuales todavía se pueden apreciar en el sitio y en el museo de la ciudad. Durante las excavaciones se encontraron muchas estatuas completas en el área del ágora y estatuas sin terminar en un área que señala el sitio de una escuela de escultura. También se han hallado sarcófagos en varios puntos de la ciudad, la mayor parte de ellos con diseños que constan de guirnaldas y columnas, al igual que pilares con diseños descritos como «manuscritos humanos» o «vivientes», representando personas, pájaros y animales envueltos en hojas de acanto.<br />En el sitio arqueológico alrededor del templo se pueden encontrar rincones ideales para mantener sexo.", 3, "Geyre Mahallesi, Kuyucak Tavas Yolu, 09385 Karacasu/Aydın, Turkey", "37.710071, 28.725108", "", "www.muze.gov.tr/aphrodisias", 2);
INSERT INTO `myX`.`loca` VALUES(739, "", "Sunio: Templo de Poseidón", 19, 10, 'El templo de Poseidón de Sunio era lo primero que veían los navegantes cuando se aproximaban al Ática', 3, "Cape Sounio, Sounio 195 00", "37.650153, 24.024572", "", "", 2);
INSERT INTO `myX`.`loca` VALUES(740, '', 'Monte Cyllene: Templo de Hermes', 19, 10, 'El templo de Hermes en el Monte Cyllene se construyó en el lugar en que, según la tradición, nació el dios', 3, '','37.939785, 22.395832','','',2);
INSERT INTO `myX`.`loca` VALUES(741, '', 'Argos: Templo de Hera', 19, 10, 'El templo de Hera en Argos bla bla bla', 3, '','37.691998, 22.775001', '','',2);
INSERT INTO `myX`.`loca` VALUES(742, '', 'Roma: Templo de Marte Ultore', 20, 10, 'El templo de Marte Ultore en Roma bla bla bla', 3, '','41.894396, 12.486927', '','',2);
INSERT INTO `myX`.`loca` VALUES(743, "", "Atenas: Templo de Hefesto (aka Thisio)", 19, 10, 'El templo de Hefesto en Atenas, erróneamente llamado Thisio, bla bla bla', 3, "Athens 105 55, Greece", "37.975588, 23.721417", "", "", 2);
INSERT INTO `myX`.`loca` VALUES(744, '', 'Naxos: Templo de Démeter', 19, 10, 'El templo de Démeter en Naxos bla bla bla..', 3, '','37.029108, 25.431321', '','',2);
INSERT INTO `myX`.`loca` VALUES(745, '', 'Naxos: Templo de Dionisio', 19, 10, 'El templo de Dionisio en Naxos bla bla bla..', 3 ,'','37.077697, 25.380779', '','',2);
/* values 1..733 reserved by Sarkodeiktes */

INSERT INTO `myX`.`practica` VALUES (8279, "", 734, "2018-01-01", "", "Excitante coito activo con eyaculación", 4, "Primera experiencia, «ἐν πορνείῳ». Con Actea (Proto?), una hieródula del templo de Afrodita en Corinto, llegó el estreno.<br />aconteció que, tras verla en la estoa del templo y seducido por su buen aspecto no dudé en ir tras ella y abordarle, antes de que alguna otra «rapaz» me quitase la presa. fue fácil; no dudó mucho en venirse conmigo. fuimos al fornix que ella frecuenta, y echamos un polvo «de película». a causa de la calidad del género que tenía entre manos, yo estaba excitadísimo, y ella respondía muy, pero que muy bien. besaba como nadie y también felaba muy bien.<br />lo mejor fue cuando copulamos: ella estaba tumbada boca arriba. se abrió de piernas y mi pene entró solo, sin ningún esfuerzo. una vez con el miembro dentro de su vagina no me importó follarla un poco, aunque sin correrme dentro. y así lo hice. con lo abierta que estaba, no tuve ninguna dificultad en metérsela hasta los testículos, haciéndole estremecerse de placer.<br />
yo daba sacudidas salvajes contra su vagina muriéndome de gusto, y ella disfrutaba «como una perra», aunque la muy «cabrona» ni se tocaba; me tocaba a mí, y a veces me tocaba los testículos y la raíz del miembro para cerciorarse de que lo tenía dentro.<br />me dio mucha pena tener que sacarla cuando estaba cerca de eyacular. me masturbé salvajemente, hasta «descargar» envuelto en un inmenso placer. ella tardó bastante tiempo más en llegar al orgasmo. al principio le estimulaba yo el clítoris, y al ver que no se acababa nunca le dije que lo hiciese ella misma, y mientras tanto yo le besaba, le acariciaba los pechos y le introducía un dedo por el ano. al final llegó al orgasmo entre espasmos de placer.", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8280, "", 734, "2018-01-02", "", "Coito activo con eyaculación", 3, "esta es la experiencia número dos, experiencia vivida con XXX.<br />el sexo fué de lo más gratificante. cómodos y límpios, en una cama grande, me trató con delicadeza y dulzura. nos besamos, nos acariciamos tiérnamente. todo fué muy tierno aunque eso no quitó de disfrutar de lo más duro y placentero del sexo.<br />me propuso que la penetrase, y yo acepté nervioso. me puse timidamente el preservativo y, afortunadamente, debido a su experiencia, todo fué «sobre ruedas». se la metí de golpe, y ella se estremeció de placer. fué superexcitante.<br />no eyaculé dentro -eso hubiera sido perfecto-, pero disfrute como nunca lo habría imaginado.<br />cuando se fué me quedé completamente colado por ella.", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8281, "", 734, "2018-01-03", "", "experience", 3, "trío con XXX1 y XXX2. fue fantástico: me lo ligué con la mirada en ... . XXX1 no estaba muy convencido de ella, aunque a mí me gustaba bastante. «llevárnosla» fue muy fácil, pues en la puerta de ... le propusimos venirse con nosotros, y ella aceptó sin pensárselo.<br />fuimos con el coche a una calle sin salida, justo detrás de... . paré con el coche mirando hacia la salida, y puse el quitasol en el parabrisas. acto seguido nos pasamos a la parte de atrás, dejando a la chica en medio; me quité las botas, y no perdimos el tiempo:<br />comenzamos a besuquearnos y a acariciarnos a tres bandas, la chica respondía muy bien; nosotros dos también. nos fuimos desnudando gradualmente, y así pudimos contemplar su cuerpo en línea y su ... . una vez desnudos vimos que la chiquilla no se andaba con remilgos: a mí me felaba el miembro, mientras le daba el culo a XXX1. primero me la chupó a mí. después se dio la vuelta y ... a XXX1, y XXX1 le hizo un cunnilingus. siguió XXX2 chupando a XXX1...<br />entonces yo aproveché para ir trabajándole el clítoris. cuando pasó un rato XXX1 me vio las intenciones y le dijo: «<cite>¿Quieres que mi novio te meta la punta?</cite>», a lo que ella respondió: «<cite>Sin condón, no</cite>». entonces le dijimos: «<cite>Tenemos condones de sobra</cite>», mientras yo ya estaba cogiendo uno de mi pantalón.<br />me lo puse en el miembro, y empecé con las maniobras de penetración, aunque enseguida me di cuenta de que no iba a ser demasiado fácil. entonces me escurrí por debajo suya y empecé a lamer su culete, lo que parece que le dio mucho gusto a juzgar por los gemidos que daba. yo pensaba: «<cite>¡Cuando te meta el miembro te va a gustar todavía más!</cite>» enseguida me incorporé y retomé las maniobras, justo donde las había dejado, alcanzando con éxito la penetración anal completa en pocos segundos.<br />su cuerpo empezó a destensarse, y comenzamos a gozar. le fui dando sacudidas profundas, pero no muy fuertes, pues lo que yo quería era preparar esa conducto estrecho para que todos sintiéramos placer. la chavala emitía unos sonidos lastimeros, mezcla de placer y, al principio, de dolor; pero todo el dolor se transformó rápidamente en placer, y mi miembro entraba y salía de su culete con facilidad. XXX2 daba entonces profundos suspiros, envuelta en placer. XXX1 se masturbaba mientras la acariciaba y, a veces, ... .<br />... al tener la boca libre nos hizo notar aún más lo bien que lo estaba pasando, pues sus gemidos y suspiros eran continuos...", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8282, "", 734, "2018-01-04", "", "experience", 3, "no tuve que trabajar mucho para beneficiármela, fue un regalo del cielo. al contrario, me pilló casi por sorpresa. a ella le bastó echar un ojo al interior de mi fornix, donde estaba yo tendido desnudo, para quedarse atento a mi reacción, la cual no se hizo de esperar.<br />entró inmediatamente, y yo empecé a comerle los pezones y a deleitarme del tamaño y la dureza de su pecho. simultáneamente, comencé a explorar lo que había mas abajo de la cintura, bajo la toalla, y descubrí con mucho gusto ...<br />πὼ πώ, ¡Dios qué tiaza! me la comí viva por todas partes, intentando disfrutar lo más posible de esos momentos que normalmente no se presentan cada día. ella se mostró más fría, y no sólo no me comió en el cuerpo, sino que evitó incluso el besarme; eso no quita que disfrutase también ella como un enano de mi cuerpo serrano.<br />al poco rato de «marraneo» me di cuenta de que se dejaba trabajar el culo más de lo normal. por supuesto ella ya había reparado en el tamaño y la dureza de mi miembro, y me hizo ver claramente que quería que le metiese «caña de España». se me dio la vuelta, me puso su culo en pompa y me largó un condón (que había traído consigo).<br />se la clavé profundamente. me la follé durante un buen rato, y mientras la follaba recorría con mis manos y mi boca su cuerpo de Venus. ella se sometía sumisamente a los viajes de mi pene erecto, y comprobaba de cuando en cuando la placentera presencia de mi miembro en su ojete. cambiamos dos veces de postura, y acabamos finalmente la cópula estando ella tumbada boca arriba, lo cual me dio la oportunidad de disfrutar plenamente de la contemplación de su cuerpazo mientras la follaba, y aún deleitarme de la caricia fogaz de su pecho terso.<br />en estas condiciones hubiera sido difícil no eyacular, lo cual hice encantado haciéndole ver abiertamente de qué modo gozaba. al momento me estaba haciendo un gesto de dolor para que se la sacara del culo, tan fría como ella misma lo había sido durante todo el rato.<br />fue apoteósico. magnífico. maravilloso. un polvo para no olvidar.<br />ella se comportó como una «cabrona» folladora, tan fría, tan bien equipada, tan sumisa... yo me comporté como un «cabrón» follador, tan sintabúes, tan dominante, tan «<i>yo me corro; tú haz lo que quieras</i>». comprensión total. disfrute pleno.<br />me pedía después del polvo que encendiese la luz: «<cite>Es ist ein Bisschen dunkel hier, oder?</cite>» quería ver con detalle al toro que se la había follado. la impresión debió resultar -espero- positiva. sin embargo, para no variar, siguió comportándose tan fríamente como lo había hecho todo el rato, y se largó al momento con un simple «<i>Tschüß</i>».<br />no importa. el disfrute que tuve con la cópula me había dejado totalmente satisfecho... y casi exhausto.", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8283, "", 734, "2018-01-05", "", "experience", 3, "se lo estaban montando con mucha calma -μτγν «<i>τὰ παιδία παίζει</i>»-, a la espera de un tercer vértice para el triángulo. entonces aparecí yo.<br />después de un rato no corto de marraneo inicial copulé con ambas; empecé por la que parecía más joven, y durante un rato bastante grande le penetré con fuerza y ganas.<br />después la otra, envidiosa, le dijo que ella también quería, por lo que cambiaron, y me follé a la otra con la fuerza de un toro salvaje. la «cabrona» disfrutó como una «puta perra», y los gritos que daban no parecían ser humanos.<br />después del polvo (ambas se corrieron, yo no), «flipaban» entre ellas de ver cómo me las había follado. me miraban y sonreían. yo estaba bañado en sudor.", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8284, "", 734, "2018-01-06", "", "experience", 3, "la segunda vez con él -por cierto, ella no me reconoció-, no hizo falta demasiado flirteo para comprender nuestras intenciones: nos deseábamos.<br />entré en ... ; me siguió; nos enrollamos de inmediato. con mucho frenesí nos comimos la boca, nos estrujamos, «nos dimos caña». la manoseé viva, y ella hizo lo mismo conmigo. me feló el miembro (en bastantes ocasiones) haciéndome un «<i>deep-throat</i>» tan regular y bien hecho que llegó a asombrarme. le trabajé el clítoris a base de bien. πὼ πώ, ¡qué bueno!<br />después de un rato de trajineo en ese «agujero del placer» me la follé viva un montón de ocasiones, utilizando para ello nada menos que cuatro condones diferentes. y entre clavada y clavada «marraneábamos», nos comíamos las bocas.<br />asumo que acabé eyaculando.", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8285, "", 734, "2018-01-07", "", "experience", 3, "nos enrollamos en un rincón oscuro; luego fuimos a un fornix.<br />se puso hecha una «zorra», me manoseó y me comió vivo. se mediodesnudó, se arrodilló ante mí, y me la comió enteretita.<br />mientras, yo ya le había estado palpando el ano: follastible. seguí durante un rato «trabajándole» el culete; ella con la <i>fellatio</i>. así que, al poco rato, se ofreció a ser follada. ante mi respuesta afirmativa, se terminó de desnudar, se colocó en el <i>sling</i>, se abrió de piernas.<br />le clavé la punta de mi miembro en su ano abierto y, en lugar de follarlo, hice balancear muy despacito el <i>sling</i> de modo que mi pene le entraba y salía muy, muy despacio, disfrutando al máximo su culete en cada milímetro de mi miembro tieso. πὼ πώ, ¡fué totalmente «<i>geil</i>»! entonces le pregunté si le gustaba más de esa manera o de... «<cite>¡Ésta!</cite>», dije, mientras se la clavava con la fuerza de un toro salvaje. le encantó, a la «zorra». me dijo que era un buen follador. le estuve metiendo embestidas un buen rato...<br />me había pedido que eyaculase en sus pechos, y había llegado el momento. se la saqué, rodeé el <i>sling</i> y se la metí en la boca, que la tenía abierta con la cabeza girada hacia atrás. <i>deep throat</i>. tanto, que hasta me dolía.<br />al ratito se la saqué y, masturbándome frenéticamente, eyaculé descargando toda mi virilidad en sus pechos, cuello y pecho. entonces llegó ella al orgasmo, masturbándose.<br />le encantó, a la «perra». se quedó flipando. no paró de elogiarme.<br /><i>intermission...</i>", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8286, "", 734, "2018-01-08", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8287, "", 735, "2018-01-09", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8288, "", 735, "2018-01-10", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8289, "", 735, "2018-01-11", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8290, "", 735, "2018-01-12", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8291, "", 735, "2018-01-13", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8292, "", 735, "2018-01-14", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8293, "", 735, "2018-01-15", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8294, "", 735, "2018-01-16", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8295, "", 736, "2018-01-17", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8296, "", 736, "2018-01-18", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8297, "", 736, "2018-01-19", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8298, "", 736, "2018-01-20", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8299, "", 736, "2018-01-21", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8300, "", 736, "2018-01-22", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8301, "", 736, "2018-01-23", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8302, "", 736, "2018-01-24", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8303, "", 737, "2018-01-25", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8304, "", 737, "2018-01-26", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8305, "", 737, "2018-01-27", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8306, "", 737, "2018-01-28", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8307, "", 737, "2018-01-29", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8308, "", 737, "2018-01-30", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8309, "", 737, "2018-01-31", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8310, "", 737, "2018-02-01", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8311, "", 738, "2018-02-02", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8312, "", 738, "2018-02-03", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8313, "", 738, "2018-02-04", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8314, "", 738, "2018-02-05", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8315, "", 738, "2018-02-06", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8316, "", 738, "2018-02-07", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8317, "", 738, "2018-02-08", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8318, "", 738, "2018-02-09", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8319, "", 738, "2018-02-10", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8320, "", 739, "2018-02-11", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8321, "", 739, "2018-02-12", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8322, "", 739, "2018-02-13", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8323, "", 739, "2018-02-14", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8324, "", 739, "2018-02-15", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8325, "", 739, "2018-02-16", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8326, "", 739, "2018-02-17", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8327, "", 739, "2018-02-18", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8328, "", 739, "2018-02-19", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8329, "", 740, "2018-02-20", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8330, "", 740, "2018-02-21", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8331, "", 740, "2018-02-22", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8332, "", 740, "2018-02-23", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8333, "", 740, "2018-02-24", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8334, "", 740, "2018-02-25", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8335, "", 740, "2018-02-26", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8336, "", 740, "2018-02-27", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8337, "", 741, "2018-02-28", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8338, "", 741, "2018-03-01", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8339, "", 741, "2018-03-02", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8340, "", 741, "2018-03-03", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8341, "", 741, "2018-03-04", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8342, "", 741, "2018-03-05", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8343, "", 741, "2018-03-06", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8344, "", 742, "2018-03-07", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8345, "", 742, "2018-03-08", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8346, "", 742, "2018-03-09", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8347, "", 742, "2018-03-10", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8348, "", 742, "2018-03-11", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8349, "", 742, "2018-03-12", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8350, "", 742, "2018-03-13", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8351, "", 742, "2018-03-14", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8352, "", 743, "2018-03-15", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8353, "", 743, "2018-03-16", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8354, "", 743, "2018-03-17", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8355, "", 743, "2018-03-18", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8356, "", 743, "2018-03-19", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8357, "", 743, "2018-03-20", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8358, "", 743, "2018-03-21", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8359, "", 743, "2018-03-22", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8360, "", 744, "2018-03-23", "", "Coito activo con eyaculación", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8361, "", 744, "2018-03-24", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8362, "", 744, "2018-03-25", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8363, "", 744, "2018-03-26", "", "Juego carnal con eyaculación", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8364, "", 744, "2018-03-27", "", "Coito activo sin eyaculación", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8365, "", 744, "2018-03-28", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8366, "", 744, "2018-03-29", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8367, "", 744, "2018-03-30", "", "Fellatio pasiva con eyaculación", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8368, "", 745, "2018-03-31", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8369, "", 745, "2018-04-01", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8370, "", 745, "2018-04-02", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8371, "", 745, "2018-04-03", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8372, "", 745, "2018-04-04", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8373, "", 745, "2018-04-05", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8374, "", 745, "2018-04-06", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8375, "", 745, "2018-04-07", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8376, "", 734, "2018-04-08", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8377, "", 734, "2018-04-09", "", "experience", 3, "Lorem ipsum", 3, 1, 0, 2);
INSERT INTO `myX`.`practica` VALUES (8378, "", 734, "2018-04-20", "", "Excitante coito activo con eyaculación", 4, "Con Eucranta, la que concede coronar el fin, terminan mis aventuras amorosas.<br />Ocurrió que...", 3, 1, 1, 2);
/* values 1..8278 reserved by Sarkodeiktes */

INSERT INTO `myX`.`amores` VALUES (5869, "", "Actea, la de los acantilados", 2, "Actea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "Skype: actea1973; Badoo: actea1973; Instagram: actea1973", "Actea María Pérez Pérez", 0, "(+34) 661 662 663", "actea@gmail.com", "fecha de nacimiento: 1973-01-01", 2);
INSERT INTO `myX`.`amores` VALUES (5870, "", "Ágava, la resplandeciente", 2, "Ágava es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5871, "", "Amatea, la de hermosos bucles", 2, "Amatea es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5872, "", "Anfínoma", 2, "Anfínoma es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5873, "", "Anfítoa", 2, "Anfítoa es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5874, "", "Anfítrite, la de bellos tobillos", 2, "Anfítrite es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5875, "", "Apseudes", 2, "Apseudes es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5876, "", "Autónoe, la que se entiende a sí misma", 2, "Autónoe es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5877, "", "Calianasa", 2, "Calianasa es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5878, "", "Calianira", 2, "Calianira es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5879, "", "Calipso", 2, "Calipso es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5880, "", "Ceto", 2, "Ceto es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5881, "", "Cimatolega, la que calma el oleaje", 2, "Cimatolega es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5882, "", "Cimo, la de las olas", 2, "Cimo es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5883, "", "Cimódoce, la que recibe las olas, la que calma sin esfuerzo el oleaje en el sombrío ponto y las rafagas de los vientos huracanados", 2, "Cimódoce es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5884, "", "Cimótoa, la de rápidas olas", 2, "Cimótoa es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5885, "", "Clímena", 2, "Clímena es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5886, "", "Clío", 2, "Clío es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5887, "", "Cranto", 2, "Cranto así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5888, "", "Dero", 2, "Dero es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5889, "", "Dexamena", 2, "Dexamena es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5890, "", "Dinámena, la potente", 2, "Dinámena es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5891, "", "Dione", 2, "Dione es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5892, "", "Doris, la que regala", 2, "Doris es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5893, "", "Doto, la dadivosa", 2, "Doto es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5894, "", "Érato, la deliciosa", 2, "Érato es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5895, "", "Espío, la de las grutas", 2, "Espío es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5896, "", "Eucranta, la que concede coronar el fin", 2, "Eucranta es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5897, "", "Eudora, la que da prosperidad", 2, "Eudora es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5898, "", "Eulímene, la de buen puerto", 2, "Eulímene es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5899, "", "Eumolpe", 2, "Eumolpe es así y asao", "Cuerpo tal y tal", "Pecho tal y tal", "Genitales tal y tal", 3, "", "", 0, "(+34) XXX", "XXX@gmail.com", "", 2);
INSERT INTO `myX`.`amores` VALUES (5900, "", "Eunice, la de fácil victoria, la de rosados brazos", 2, "Eunice es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5901, "", "Eupompa, la de feliz viaje", 2, "Eupompa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5902, "", "Eurídice", 2, "Eurídice es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5903, "", "Evágora,la elocuente", 2, "Evágora es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5904, "", "Evarna, la rica en ganado, la de encantadora figura y belleza sin tacha", 2, "Evarna es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5905, "", "Éyone, la del fondeadero", 2, "Éynoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5906, "", "Ferusa, la que lleva", 2, "Ferusa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5907, "", "Galatea, la hermosa, la muy ilustre", 2, "Galatea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5908, "", "Galena, la calma", 2, "Galena es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5909, "", "Glauca, la azulada", 2, "Glauca es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5910, "", "Glaucónoma, la del azulado prado, la risueña", 2, "Glaucónoma es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5911, "", "Halía, la salada, la amable, la de inmensos ojos", 2, "Halía es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5912, "", "Halimeda, la que cuida del mar, la de bella corona", 2, "Halimeda es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5913, "", "Hipónoe, la inteligente como un caballo, la de rosados brazos", 2, "Hipónoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5914, "", "Hipótoa, la veloz como un caballo, la encantadora", 2, "Hipótoa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5915, "", "Iera", 2, "Iera es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5916, "", "Laomedea, la que cuida del pueblo", 2, "Laomedea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5917, "", "Leágora, la de la suave palabra", 2, "Leágora es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5918, "", "Limnoria", 2, "Limnoria es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5919, "", "Lisiánasa, la señora de la libertad", 2, "Lisiánasa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5920, "", "Mélita, la dulce, la graciosa", 2, "Mélita es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5921, "", "Menipa, la del vigor de caballo, la divina", 2, "Menipa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5922, "", "Mera", 2, "Mera es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5923, "", "Nausítoe", 2, "Nausítoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5924, "", "Nemertes, la sin tacha, la que tiene la inteligencia de su inmortal padre", 2, "Nemertes es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5925, "", "Neómeris", 2, "Neómeris es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5926, "", "Nesea, la isleña", 2, "Nesea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5927, "", "Neso, la isla", 2, "Neso es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5928, "", "Oritía", 2, "Oritía es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5929, "", "Pánopa, la que todo lo ve", 2, "Pánopa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5930, "", "Pasítea, la muy divina", 2, "Pasítea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5931, "", "Plexaura", 2, "Plexaura es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5932, "", "Ploto, la naviera", 2, "Ploto es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5933, "", "Polínoe, la que mucho entiende", 2, "Polínoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5934, "", "Polínome", 2, "Polínome es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5935, "", "Pontomedusa", 2, "Pontomedusa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5936, "", "Prónoe, la previsora", 2, "Prónoe es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5937, "", "Proto, la primera", 2, "Proto es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5938, "", "Protomedea, la primera en pensamientos", 2, "Protomedea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5939, "", "Protoporea, la que permite atravesar el ponto", 2, "Protoporea es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5940, "", "Psámata, la arenosa, la de gracioso porte", 2, "Psámata es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5941, "", "Sao, la salvadora", 2, "Sao es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5942, "", "Talía", 2, "Talía es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5943, "", "Temisto, la observadora de las leyes divinas", 2, "Temisto es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5944, "", "Tetis", 2, "Tetis es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5945, "", "Toa, la rápida", 2, "Toa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5946, "", "Yanasa", 2, "Yanasa es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5947, "", "Yanira", 2, "Yanira es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
INSERT INTO `myX`.`amores` VALUES (5948, "", "Yone", 2, "Yone es así y asao", "Tiene un cuerpo tal y tal", "Tiene un pecho tal y tal", "", 3, "", "", 0, "", "", "", 2);
/* values 1..5868 reserved by Sarkodeiktes */

INSERT INTO `myX`.`assignations` VALUES (8279, 5869);
INSERT INTO `myX`.`assignations` VALUES (8280, 5870);
INSERT INTO `myX`.`assignations` VALUES (8281, 5871);
INSERT INTO `myX`.`assignations` VALUES (8282, 5872);
INSERT INTO `myX`.`assignations` VALUES (8283, 5873);
INSERT INTO `myX`.`assignations` VALUES (8284, 5874);
INSERT INTO `myX`.`assignations` VALUES (8285, 5875);
INSERT INTO `myX`.`assignations` VALUES (8286, 5876);
INSERT INTO `myX`.`assignations` VALUES (8287, 5877);
INSERT INTO `myX`.`assignations` VALUES (8288, 5878);
INSERT INTO `myX`.`assignations` VALUES (8289, 5879);
INSERT INTO `myX`.`assignations` VALUES (8290, 5880);
INSERT INTO `myX`.`assignations` VALUES (8291, 5881);
INSERT INTO `myX`.`assignations` VALUES (8292, 5882);
INSERT INTO `myX`.`assignations` VALUES (8293, 5883);
INSERT INTO `myX`.`assignations` VALUES (8294, 5884);
INSERT INTO `myX`.`assignations` VALUES (8295, 5885);
INSERT INTO `myX`.`assignations` VALUES (8296, 5886);
INSERT INTO `myX`.`assignations` VALUES (8297, 5887);
INSERT INTO `myX`.`assignations` VALUES (8298, 5888);
INSERT INTO `myX`.`assignations` VALUES (8299, 5889);
INSERT INTO `myX`.`assignations` VALUES (8300, 5900);
INSERT INTO `myX`.`assignations` VALUES (8301, 5901);
INSERT INTO `myX`.`assignations` VALUES (8302, 5902);
INSERT INTO `myX`.`assignations` VALUES (8303, 5903);
INSERT INTO `myX`.`assignations` VALUES (8304, 5904);
INSERT INTO `myX`.`assignations` VALUES (8305, 5905);
INSERT INTO `myX`.`assignations` VALUES (8306, 5906);
INSERT INTO `myX`.`assignations` VALUES (8307, 5907);
INSERT INTO `myX`.`assignations` VALUES (8308, 5908);
INSERT INTO `myX`.`assignations` VALUES (8309, 5909);
INSERT INTO `myX`.`assignations` VALUES (8310, 5910);
INSERT INTO `myX`.`assignations` VALUES (8311, 5911);
INSERT INTO `myX`.`assignations` VALUES (8312, 5912);
INSERT INTO `myX`.`assignations` VALUES (8313, 5913);
INSERT INTO `myX`.`assignations` VALUES (8314, 5914);
INSERT INTO `myX`.`assignations` VALUES (8315, 5915);
INSERT INTO `myX`.`assignations` VALUES (8316, 5916);
INSERT INTO `myX`.`assignations` VALUES (8317, 5917);
INSERT INTO `myX`.`assignations` VALUES (8318, 5918);
INSERT INTO `myX`.`assignations` VALUES (8319, 5919);
INSERT INTO `myX`.`assignations` VALUES (8320, 5920);
INSERT INTO `myX`.`assignations` VALUES (8321, 5921);
INSERT INTO `myX`.`assignations` VALUES (8322, 5922);
INSERT INTO `myX`.`assignations` VALUES (8323, 5923);
INSERT INTO `myX`.`assignations` VALUES (8324, 5924);
INSERT INTO `myX`.`assignations` VALUES (8325, 5925);
INSERT INTO `myX`.`assignations` VALUES (8326, 5926);
INSERT INTO `myX`.`assignations` VALUES (8327, 5927);
INSERT INTO `myX`.`assignations` VALUES (8328, 5928);
INSERT INTO `myX`.`assignations` VALUES (8329, 5929);
INSERT INTO `myX`.`assignations` VALUES (8330, 5930);
INSERT INTO `myX`.`assignations` VALUES (8331, 5931);
INSERT INTO `myX`.`assignations` VALUES (8332, 5932);
INSERT INTO `myX`.`assignations` VALUES (8333, 5933);
INSERT INTO `myX`.`assignations` VALUES (8334, 5934);
INSERT INTO `myX`.`assignations` VALUES (8335, 5935);
INSERT INTO `myX`.`assignations` VALUES (8336, 5936);
INSERT INTO `myX`.`assignations` VALUES (8337, 5937);
INSERT INTO `myX`.`assignations` VALUES (8338, 5938);
INSERT INTO `myX`.`assignations` VALUES (8339, 5939);
INSERT INTO `myX`.`assignations` VALUES (8340, 5940);
INSERT INTO `myX`.`assignations` VALUES (8341, 5941);
INSERT INTO `myX`.`assignations` VALUES (8342, 5942);
INSERT INTO `myX`.`assignations` VALUES (8343, 5943);
INSERT INTO `myX`.`assignations` VALUES (8344, 5944);
INSERT INTO `myX`.`assignations` VALUES (8345, 5945);
INSERT INTO `myX`.`assignations` VALUES (8346, 5946);
INSERT INTO `myX`.`assignations` VALUES (8347, 5947);
INSERT INTO `myX`.`assignations` VALUES (8348, 5948); /* max amorID */
INSERT INTO `myX`.`assignations` VALUES (8349, 5948);
INSERT INTO `myX`.`assignations` VALUES (8350, 5948);
INSERT INTO `myX`.`assignations` VALUES (8351, 5948);
INSERT INTO `myX`.`assignations` VALUES (8352, 5948);
INSERT INTO `myX`.`assignations` VALUES (8353, 5948);
INSERT INTO `myX`.`assignations` VALUES (8354, 5948);
INSERT INTO `myX`.`assignations` VALUES (8355, 5948);
INSERT INTO `myX`.`assignations` VALUES (8356, 5948);
INSERT INTO `myX`.`assignations` VALUES (8357, 5948);
INSERT INTO `myX`.`assignations` VALUES (8358, 5948);
INSERT INTO `myX`.`assignations` VALUES (8359, 5948);
INSERT INTO `myX`.`assignations` VALUES (8360, 5948);
INSERT INTO `myX`.`assignations` VALUES (8361, 5948);
INSERT INTO `myX`.`assignations` VALUES (8362, 5948);
INSERT INTO `myX`.`assignations` VALUES (8363, 5948);
INSERT INTO `myX`.`assignations` VALUES (8364, 5948);
INSERT INTO `myX`.`assignations` VALUES (8365, 5948);
INSERT INTO `myX`.`assignations` VALUES (8366, 5948);
INSERT INTO `myX`.`assignations` VALUES (8367, 5948);
INSERT INTO `myX`.`assignations` VALUES (8368, 5948);
INSERT INTO `myX`.`assignations` VALUES (8369, 5948);
INSERT INTO `myX`.`assignations` VALUES (8370, 5948);
INSERT INTO `myX`.`assignations` VALUES (8371, 5948);
INSERT INTO `myX`.`assignations` VALUES (8372, 5948);
INSERT INTO `myX`.`assignations` VALUES (8373, 5948);
INSERT INTO `myX`.`assignations` VALUES (8374, 5948);
INSERT INTO `myX`.`assignations` VALUES (8375, 5948);
INSERT INTO `myX`.`assignations` VALUES (8376, 5948);
INSERT INTO `myX`.`assignations` VALUES (8377, 5948);
INSERT INTO `myX`.`assignations` VALUES (8378, 5948);
INSERT INTO `myX`.`assignations` VALUES (8378, 5896);